# docker-compose.yml
version: '3'

services:
  bitwarden:
    image: bitwardenrs/server:raspberry
    restart: always
    volumes:
      - bw-data:/data
    environment:
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
      SIGNUPS_ALLOWED: 'false'   # set to false to disable signups
      ADMIN_TOKEN: 
      SMTP_HOST: smtp.gmail.com
      SMTP_FROM: bitwarden@focusedcreations.com
      SMTP_PORT: '587'
      SMTP_SSL: 'true'
      DOMAIN: 'https://bitwarden2.focusedcreations.com:2345'
      SMTP_USERNAME: 
      SMTP_PASSWORD: 

  caddy:
    image: arm32v6/caddy:alpine
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_config:/config
    ports:
      - 80:80 # needed for Let's Encrypt
      - 443:443
      - 2345:2345
    environment:
      ACME_AGREE: 'true'              # agree to Let's Encrypt Subscriber Agreement
      EMAIL: 'jonesmac82@gmail.com'  # CHANGE THIS! Optional, provided to Let's Encrypt

  bitwarden_backup:
    image: bruceforce/bw_backup:rpi3
    container_name: bitwarden_backup
    restart: on-failure
    # uncomment to debug
    #entrypoint: /bin/sh
    depends_on:
      - bitwarden
    volumes:
      - bw-data:/data/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
        # uncomment this if you want your backup to be written to ./backup/ folder"
      - bw-data:/backup_folder/
    environment:
      - DB_FILE=/data/db.sqlite3
        # uncomment this if you want your backup to be written to ./backup/ folder"
      - BACKUP_FILE=/backup_folder/backups/db.sqlite3
      - CRON_TIME=0 5 1 * *
      - TIMESTAMP=true
      - UID=0
      - GID=0

volumes:
  bw-data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/data     
      o: bind
      
