services:
  bitwarden:
    image: vaultwarden/server:1.33.2
    restart: always
    volumes:
      - bw-data:/data
    environment:
      SIGNUPS_ALLOWED: 'false'   # set to false to disable signups
      SMTP_HOST: smtp.gmail.com
      SMTP_FROM: bitwarden@focusedcreations.com
      SMTP_PORT: '587'
      SMTP_SECURITY: 'starttls'
      DOMAIN: 'https://bitwarden.focusedcreations.com'
      SMTP_USERNAME:
      SMTP_PASSWORD: 
    ports:
      - 8001:80
    networks:
      - caddy_server_pi 

  bitwarden_backup:
    image: bruceforce/vaultwarden-backup:latest
    container_name: bitwarden_backup
    restart: on-failure
    depends_on:
      - bitwarden
    volumes:
      - bw-data:/data/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
        # uncomment this if you want your backup to be written to ./backup/ folder"
      - bw-data:/backup_folder/
    environment:
      - VW_DATABASE_URL=/data/db.sqlite3
        # uncomment this if you want your backup to be written to ./backup/ folder"
      - BACKUP_DIR=/backup_folder/backups/db.sqlite3
      - CRON_TIME=0 5 * * *
      - TIMESTAMP=true
      - UID=0
      - GID=0

networks:
  caddy_server_pi:
    external: true

volumes:
  caddy_data:
  caddy_config:
  bw-data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/data     
      o: bind
      
